export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{backgroundColor: "rgba(242, 243, 247, 1)"}}>{children}</body>
    </html>
  )
}
